spring.application.name=edunest
server.port=8081

#DataBase connection
spring.datasource.url=jdbc:postgresql://localhost:5432/EduNest
spring.datasource.username=postgres
spring.datasource.password=Harshid313@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Send Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harshidpatel313@gmail.com
spring.mail.password=iiqn buyo wsmh tetp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT TOKEN
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007a0b1c2d3e4f6ag6h7i8j9k1l2m3n4o5p6q7r8s9t1u2v3w4x5y6z7
security.jwt.expiration-time=3600000

# APP_KEY & APP_IV
APP_KEY=E946C8MJ278CD5931769B241E695D8E2
APP_IV=1769B241E695D8E2