spring.application.name=edunest
server.port=8081

#DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=Harshid313@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Send Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harshidpatel313@gmail.com
spring.mail.password=iiqn buyo wsmh tetp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true